language: python
python: "3.6"
sudo: required

services:
  - docker

before_install:
  - pip install pipenv
install:
  - pipenv sync --dev

jobs:
  include:
    - stage: Test
      script: python -m pytest
    - stage: Lint
      script: flake8
    - stage: Coverage
      script: codecov
