language: python
python: "3.6"
sudo: required

services:
  - docker

before_install:
  - pip install pipenv
install:
  - pipenv sync --dev

jobs:
  include:
    - stage: Tests
      script:
        - coverage run --source whaleherder -m pytest
        - coverage report
        - codecov
    - stage: Lint
      script: flake8
