language: python
python: "3.6"
sudo: required

services:
  - docker

jobs:
  include:
    - stage: Lint
      script: flake8
    - stage: Tests
      script:
        - coverage run --source whaleherder -m pytest
        - coverage report
        - codecov
